TTbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  slide_rail_joint_position_controller:
    type: ttbot_velocity_controllers/JointProfilePositionController
    joint: joint_0
    ppm_param: {vel: 0.5, acc: 2.0, dec: 2.0}
  arm_joint1_position_controller:
    type: ttbot_velocity_controllers/JointProfilePositionController
    joint: joint_1
    ppm_param: {vel: 0.4, acc: 0.5, dec: 0.5}
  arm_joint2_position_controller:
    type: ttbot_velocity_controllers/JointProfilePositionController
    joint: joint_2
    ppm_param: {vel: 0.4, acc: 0.5, dec: 0.5}
  arm_joint3_position_controller:
    type: ttbot_velocity_controllers/JointProfilePositionController
    joint: joint_3
    ppm_param: {vel: 0.4, acc: 0.5, dec: 0.5}
  arm_joint4_position_controller:
    type: ttbot_velocity_controllers/JointProfilePositionController
    joint: joint_4
    ppm_param: {vel: 0.4, acc: 0.5, dec: 0.5}
