two_joint_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  arm_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
