<?xml version="1.0"?>
<robot name="linear_slide_rail" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="pi" value="3.1415" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_length" value="1.6" />
    <xacro:property name="base_height" value="0.6" />
    <xacro:property name="slide_rail_width" value="0.02" />
    <xacro:property name="slide_rail_length" value="1.5" />
    <xacro:property name="slide_rail_height" value="0.02" />
    <xacro:property name="slide_block_width" value="0.13" />
    <xacro:property name="slide_block_length" value="0.13" />
    <xacro:property name="slide_block_height" value="0.02" />

    <xacro:property name="j2_block1_width" value="0.11" />
    <xacro:property name="j2_block1_height" value="0.15" />

    <xacro:property name="j2_block2_radius" value="0.05" />
    <xacro:property name="j2_block2_height" value="0.07" />

    <xacro:property name="j2_block3_radius" value="0.065" />
    <xacro:property name="j2_block3_height" value="0.015" />
    
    <xacro:property name="j2_block4_width" value="0.05" />
    <xacro:property name="j2_block4_length" value="0.11"/>
    <xacro:property name="j2_block4_height" value="0.07"/>

    <xacro:property name="j2_block5_radius" value="0.055"/>
    <xacro:property name="j2_block5_height" value="0.05"/>

    <xacro:property name="j3_block1_radius" value="0.02"/>
    <xacro:property name="j3_block1_height" value="0.05"/>

    <xacro:property name="j3_block2_width" value="0.02"/>
    <xacro:property name="j3_block2_length" value="0.05"/>
    <xacro:property name="j3_block2_height" value="0.3"/>

    <xacro:property name="j4_block1_radius" value="0.02"/>
    <xacro:property name="j4_block1_height" value="0.05"/>

    <xacro:property name="j4_block2_width" value="0.02"/>
    <xacro:property name="j4_block2_length" value="0.05"/>
    <xacro:property name="j4_block2_height" value="0.20"/>

    <xacro:property name="j5_block1_radius" value="0.02"/>
    <xacro:property name="j5_block1_height" value="0.05"/>

    <xacro:property name="j5_block2_width" value="0.02"/>
    <xacro:property name="j5_block2_length" value="0.05"/>
    <xacro:property name="j5_block2_height" value="0.15"/>



    <!-- include gazebo file -->
    <xacro:include filename="$(find robot_description)/urdf/linear_slide_rail.gazebo" />








    <material name="gray">
        <color rgba="${100/255} ${100/255} ${100/255} 1.0"/>
    </material>

    <material name="white">
        <color rgba="${255/255} ${255/255} ${255/255} 1.0"/>
    </material>

    <material name="blue">
        <color rgba="${0/255} ${0/255} ${230/255} 1.0"/>
    </material>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}" />
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>

    <xacro:macro name="slide_rail" params="prefix reflect">
        <link name="${prefix}_slide_rail">
            <visual>
                <geometry>
                    <box size="${slide_rail_width} ${slide_rail_length} ${slide_rail_height}" />
                </geometry>
                <origin xyz="0 0 ${slide_rail_height/2}" rpy="0 0 0" />
                <material name="gray"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${slide_rail_width} ${slide_rail_length} ${slide_rail_height}" />
                </geometry>
                <origin xyz="0 0 ${slide_rail_height/2}" rpy="0 0 0" />
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>
        <joint name="base_to_${prefix}_slide_rail" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_slide_rail"/>
            <origin xyz="${reflect} 0 ${base_height/2}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
    
    <xacro:slide_rail prefix="r" reflect="0.05"/>
    <xacro:slide_rail prefix="l" reflect="-0.05"/>
    
    <joint name="slide_rail_joint" type="prismatic">
        <parent link="r_slide_rail"/>
        <child link="slide_block_base"/>
        <limit effort="10.0" lower="-0.7" upper="0.7" velocity="0.5"/>
        <origin xyz="-0.05 0 ${slide_rail_height}"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 1 0"/>
    </joint>
    <link name="slide_block_base">
        <visual>
            <geometry>
                <box size="${slide_block_width} ${slide_block_length} ${slide_block_height}"/>
            </geometry>
            <origin xyz="0 0 ${slide_block_height/2}"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${slide_block_width} ${slide_block_length} ${slide_block_height}"/>
            </geometry>
            <origin xyz="0 0 ${slide_block_height/2}"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="slide_block_to_j2block1" type="fixed">
        <parent link="slide_block_base"/>
        <child link="j2_block1"/>
        <origin xyz="0 0 ${slide_block_height}"/>
    </joint>
    <link name="j2_block1">
        <visual>
            <geometry>
                <box size="${j2_block1_width} ${j2_block1_width} ${j2_block1_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block1_height/2}"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${j2_block1_width} ${j2_block1_width} ${j2_block1_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block1_height/2}"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="base_arm_joint" type="revolute">
        <parent link="j2_block1"/>
        <child link="j2_block2"/>
        <limit effort="1000.0" lower="${-pi*3/4}" upper="${pi*3/4}" velocity="0.5"/>
        <origin xyz="0 0 ${j2_block1_height}"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="j2_block2">
        <visual>
            <geometry>
                <cylinder radius="${j2_block2_radius}" length="${j2_block2_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j2_block2_radius}" length="${j2_block2_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j2block2_to_3" type="fixed">
        <parent link="j2_block2"/>
        <child link="j2_block3"/>
        <origin xyz="0 0 ${j2_block2_height/2}"/>
    </joint>
    <link name="j2_block3">
        <visual>
            <geometry>
                <cylinder radius="${j2_block3_radius}" length="${j2_block3_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block3_height/2}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j2_block3_radius}" length="${j2_block3_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block3_height/2}" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j2block3_to_4" type="fixed">
        <parent link="j2_block3"/>
        <child link="j2_block4"/>
        <origin xyz="0 0 ${j2_block3_height}"/>
    </joint>
    <link name="j2_block4">
        <visual>
            <geometry>
                <box size="${j2_block4_width} ${j2_block4_length} ${j2_block4_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block4_height/2}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${j2_block4_width} ${j2_block4_length} ${j2_block4_height}"/>
            </geometry>
            <origin xyz="0 0 ${j2_block4_height/2}" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j2block4_to_5" type="fixed">
        <parent link="j2_block4"/>
        <child link="j2_block5"/>
        <origin xyz="0 0 ${j2_block4_height}"/>
    </joint>
    <link name="j2_block5">
        <visual>
            <geometry>
                <cylinder radius="${j2_block5_radius}" length="${j2_block5_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j2_block5_radius}" length="${j2_block5_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="arm_2_joint" type="revolute">
        <parent link="j2_block5"/>
        <child link="j3_block1"/>
        <limit effort="1000.0" lower="${-pi*3/4}" upper="${pi*3/4}" velocity="0.5"/>
        <origin xyz="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="1 0 0"/>
    </joint>
    <link name="j3_block1">
        <visual>
            <geometry>
                <cylinder radius="${j3_block1_radius}" length="${j3_block1_height}"/>
            </geometry>
            <origin xyz="${-j3_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j3_block1_radius}" length="${j3_block1_height}"/>
            </geometry>
            <origin xyz="${-j3_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j3block1_to_2" type="fixed">
        <parent link="j3_block1"/>
        <child link="j3_block2"/>
        <origin xyz="${-j3_block1_height} 0 0"/>
    </joint>
    <link name="j3_block2">
        <visual>
            <geometry>
                <box size="${j3_block2_width} ${j3_block2_length} ${j3_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j3_block2_height*3/8}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${j3_block2_width} ${j3_block2_length} ${j3_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j3_block2_height*3/8}" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="arm_3_joint" type="revolute">
        <parent link="j3_block2"/>
        <child link="j4_block1"/>
        <limit effort="1000.0" lower="${-pi*3/4}" upper="${pi*3/4}" velocity="0.5"/>
        <origin xyz="0 0 ${j3_block2_height*6/8}"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="1 0 0"/>
    </joint>
    <link name="j4_block1">
        <visual>
            <geometry>
                <cylinder radius="${j4_block1_radius}" length="${j4_block1_height}"/>
            </geometry>
            <origin xyz="${j4_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j4_block1_radius}" length="${j4_block1_height}"/>
            </geometry>
            <origin xyz="${j4_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j4block1_to_2" type="fixed">
        <parent link="j4_block1"/>
        <child link="j4_block2"/>
        <origin xyz="${j4_block1_height} 0 0"/>
    </joint>
    <link name="j4_block2">
        <visual>
            <geometry>
                <box size="${j4_block2_width} ${j4_block2_length} ${j4_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j4_block2_height*3/8}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${j4_block2_width} ${j4_block2_length} ${j4_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j4_block2_height*3/8}" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="arm_4_joint" type="revolute">
        <parent link="j4_block2"/>
        <child link="j5_block1"/>
        <limit effort="1000.0" lower="${-pi*3/4}" upper="${pi*3/4}" velocity="0.5"/>
        <origin xyz="0 0 ${j4_block2_height*6/8}"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="1 0 0"/>
    </joint>
    <link name="j5_block1">
        <visual>
            <geometry>
                <cylinder radius="${j5_block1_radius}" length="${j5_block1_height}"/>
            </geometry>
            <origin xyz="${-j5_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${j5_block1_radius}" length="${j5_block1_height}"/>
            </geometry>
            <origin xyz="${-j5_block1_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="j5block1_to_2" type="fixed">
        <parent link="j5_block1"/>
        <child link="j5_block2"/>
        <origin xyz="${-j5_block1_height} 0 0"/>
    </joint>
    <link name="j5_block2">
        <visual>
            <geometry>
                <box size="${j5_block2_width} ${j5_block2_length} ${j5_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j5_block2_height*3/8}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${j5_block2_width} ${j5_block2_length} ${j5_block2_height}"/>
            </geometry>
            <origin xyz="0 0 ${j5_block2_height*3/8}" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
    </link>
    
    <!-- transmission -->
    <transmission name="slide_rail_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="slide_rail_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="slide_rail_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <transmission name="base_arm_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_arm_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_arm_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="arm_2_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="arm_2_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="arm_2_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="arm_3_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="arm_3_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="arm_3_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="arm_4_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="arm_4_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="arm_4_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>



</robot>


